spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moomool?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

cloud:
  aws:
    s3:
      bucket: moomool-images
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace