spring:
  sql:
    init:
      platform: h2
  jpa:
    defer-datasource-initialization : true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_batch_fetch_size : 1000
        show_sql: true
        format_sql: true
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true