spring:
  sql:
    init:
      platform: h2
  jpa:
    defer-datasource-initialization : true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_batch_fetch_size : 1000
        show_sql: true
        format_sql: true

cloud:
  aws:
    s3:
      bucket: moomool-images
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}