spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 307344693010-lp7l03o1le6f2ciotshdd07qevas458m.apps.googleusercontent.com
            clientSecret: R7wJHk71-jqSoLfhRXilR6L3
            scope : profile,email

jwt:
  secret: d2h5LWRpZC15b3UtYnV5LXRoaXMtc2VjcmV0LWtleS13aHktZGlkLXlvdS1idXktdGhpcy1zZWNyZXQta2V5
  access-token-expired-time: 86400
  refresh-token-expired-time: 1209600

cloud:
  aws:
    s3:
      bucket: moomool-images
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}